#
# Module manifest for module 'TenantPulse'
#
# Generated by: Adam Gell
#
# Generated on: 8/15/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'TenantPulse.psm1'

# Version number of this module.
ModuleVersion = '0.3.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'a2f6d0f0-6d0c-4a6b-9f7e-9c9e6f6c7c2f'

# Author of this module
Author = 'Adam Gell'

# Company or vendor of this module
CompanyName = 'Adam Gell'

# Copyright statement for this module
Copyright = '(c) 2026 Adam Gell. Licensed under MIT.'

# Description of the functionality provided by this module
Description = 'Read-only tenant health engine that evaluates Microsoft Intune and Entra configuration against a versioned set of checks, producing a deterministic, pseudonymized, scored snapshot.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.4'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(
    # TenantPulse reads the tenant exclusively through GraphKit's read-class descriptors.
    # RequiredVersion is deliberate: a newer GraphKit catalog is a different producer
    # contract and must be re-verified before TenantPulse consumes it.
    @{ ModuleName = 'GraphKit'; RequiredVersion = '0.3.0' }
)

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @()

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('Intune', 'Entra', 'TenantHealth', 'Graph')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/AdamGell/TenantPulse/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/AdamGell/TenantPulse'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
## [0.3.0] - Unreleased

### Added

- Neutral `-ReportData Applications` collection on `Get-PulseTenantSnapshot` and
  `Invoke-PulseAssessment`, producing schema-v1, hash-verified application-assignment and
  app-install-error JSONL artifacts. The contract preserves raw report columns, assignment
  targets/settings, group resolution and member-count certainty, and explicit partial/failure
  gaps without adding Office rendering, branding, approval workflow, or derived severity.
- Self-contained HTML findings reports through `Export-PulseReport -Format Html` and
  `Invoke-PulseAssessment -Format Html`. JSON remains canonical and is always written by the
  assessment path; HTML is a second findings-only renderer with inline CSS, no scripts, no
  network-loading URLs, and no Graph or snapshot access.
- TenantPulse 1.0 privacy-classification constructors for `Identity`, `SecretSensitive`,
  `SafeTechnical`, `SafeOperatorLabel`, and `BoundedReviewedText`, plus fail-closed
  `ConvertTo-PulseSafeShareDocument` conversion and privacy mutation canaries.

### Fixed

- Composite datasets now use explicit TenantPulse provider-plan metadata instead of
  synthetic GraphKit `Pending` / `Walk` descriptors. Permission preflight includes every
  declared child operation, including Endpoint Security policy assignments, while the
  Windows data-processor disposition records no Graph operation or API version.
- Endpoint Security collection now gaps absent or unrecognized template metadata instead
  of silently publishing authoritative empty results, and current security baselines are
  still collected when the independent legacy-template surface fails.
- Administrative Template expansion now honors a shared authentication abort before any
  descriptor or Graph work and gaps presentation values without stable ids instead of
  inventing random evidence identities. App Control wording now matches its confirmed-
  assignment behavior.
- Application report collection now request-body pages the Intune install summary through
  `TotalRowCount`, records incomplete totals and partial group metadata as gaps, stops every
  later report read on authentication failure, recursively scrubs tenant identifiers before
  persistence, rejects semantically unknown report matrices, and uses a canonical total-order
  tie-breaker for content-addressed rows.
- Graph collection now fails closed unless `Get-GraphObject -PassThruResult` returns exactly one complete `GraphKit.OperationResult`; null, rows-only, multiple, type-spoofed, and malformed results can no longer be persisted as `Collected`, while bounded partial rows retain indeterminate, truncation, and page-cap detail.
- Review finding 6 is implemented: Endpoint Security composite provenance now records the stable qualified primitive set `ConfigurationPolicy.ListBeta` and `ConfigurationPolicySetting.ListBeta`, independent of tenant policy count; child gaps name the setting primitive explicitly.
- Direct, composite, and expansion collection paths now use one canonical Graph failure mapper. A request-time `403` is recorded as `Failed` / `PermissionDenied`; only `AuthenticationFailed` aborts subsequent network collection, while deadline expiration, cancellation, indeterminate certainty, permission denial, and provider failure remain explicit and isolated.

### Changed

- The approved product-program completion work uses a unique successor identity. Published TenantPulse 0.2.0 and its exact GraphKit 0.3.0 dependency remain immutable.
- `Data.PartialDatasets` is a strict Function-only opt-in that requires `DatasetOutcomes`. Exactly four checks opt in: universal checks `TP.INT.0013` and `TP.INT.0029` may Fail on a known offender but cannot Pass with gaps; existential checks `TP.INT.0014` and `TP.INT.0015` may Pass on a known witness but cannot Fail with gaps. BitLocker and LAPS witnesses require native Boolean values.
- The other 49 checks remain `NotApplicable` when their dataset status is `Partial`. For the four opt-ins, a structurally valid non-decisive Partial result is also `NotApplicable`; without decisive proof, zero usable rows or malformed outcomes, gaps, or rows are `Error`.
- Findings schema `1.0`, snapshot schema `2.0.0`, and scoring model `1.0` are unchanged. This deterministic source/package tranche makes no new live-service or publication claim.
- Review finding 14 remains rejected/obsolete on first-party schema evidence: supported schema 1.0.0/1.1.0 writers could not emit `Partial`, so migration rejects that later state without rewriting the manifest.
- Classified JSON export now requires complete field classification before it emits a
  `privacy.boundary = "classified"` document. `-Redact`, `RedactDetailKeys`, and
  `Protect-PulseReason` remain the local-only compatibility layer; C0 D6 still leaves the public
  safe-share workflow undecided, and no public operator-key rotate cmdlet was added.
'@

        # Prerelease string of this module
        Prerelease =  ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
