#
# Module manifest for module 'TenantPulse'
#
# Generated by: Adam Gell
#
# Generated on: 8/15/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'TenantPulse.psm1'

# Version number of this module.
ModuleVersion = '0.3.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'a2f6d0f0-6d0c-4a6b-9f7e-9c9e6f6c7c2f'

# Author of this module
Author = 'Adam Gell'

# Company or vendor of this module
CompanyName = 'Adam Gell'

# Copyright statement for this module
Copyright = '(c) 2026 Adam Gell. Licensed under MIT.'

# Description of the functionality provided by this module
Description = 'Read-only tenant health engine that evaluates Microsoft Intune and Entra configuration against a versioned set of checks, producing a deterministic, pseudonymized, scored snapshot.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.4'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(
    # TenantPulse reads the tenant exclusively through GraphKit's read-class descriptors.
    # RequiredVersion is deliberate: a newer GraphKit catalog is a different producer
    # contract and must be re-verified before TenantPulse consumes it.
    @{ ModuleName = 'GraphKit'; RequiredVersion = '0.3.0' }
)

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @()

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('Intune', 'Entra', 'TenantHealth', 'Graph')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/AdamGell/TenantPulse/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/AdamGell/TenantPulse'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
## [0.3.0] - Unreleased

### Added

- Neutral `-ReportData Applications` collection on `Get-PulseTenantSnapshot` and
  `Invoke-PulseAssessment`, producing schema-v1, hash-verified application-assignment and
  app-install-error JSONL artifacts. The contract preserves raw report columns, assignment
  targets/settings, group resolution and member-count certainty, and explicit partial/failure
  gaps without adding Office rendering, branding, approval workflow, or derived severity.
- Self-contained HTML findings reports through `Export-PulseReport -Format Html` and
  `Invoke-PulseAssessment -Format Html`. JSON remains canonical and is always written by the
  assessment path; HTML is a second findings-only renderer with inline CSS, no scripts, no
  network-loading URLs, and no Graph or snapshot access.
- TenantPulse 1.0 privacy-classification constructors for `Identity`, `SecretSensitive`,
  `SafeTechnical`, `SafeOperatorLabel`, and `BoundedReviewedText`, plus fail-closed
  `ConvertTo-PulseSafeShareDocument` conversion and privacy mutation canaries.

### Fixed

- Conditional Access findings no longer promote policy presence to tenant-wide protection
  without evaluating effective user, resource, client-app, platform, location, risk,
  current and deprecated device, authentication-flow, workload/agent-identity, and grant
  semantics. Legacy-auth requires both legacy client buckets without letting an unknown
  ancillary condition broaden a recognized bucket. MFA checks distinguish mandatory grants
  from OR alternatives; a custom strength establishes generic MFA only when Graph reports
  `requirementsSatisfied=mfa`, and never establishes phishing resistance from that field alone.
  Unknown/future controls and invalid MFA/strength, block-sibling, password-change, or risk-
  remediation combinations remain indeterminate. Role checks use Microsoft's current 14-role
  minimum-admin baseline and treat undeclared user, group, and guest/external carve-outs as
  indeterminate, while canonical approved account exceptions remain explicit, deduplicated
  evidence. Beta authentication-context targets and time conditions retain known narrow-scope
  lower bounds, and any unrecognized non-null condition fails closed. Cross-tenant
  defaults now validate singleton cardinality and distinguish a decisive full block or
  scoped allowlist from a narrow denylist. Workload-identity awareness validates documented
  service-principal and beta agent-identity selectors and filters, reports malformed policies
  separately, and does not count the tenant-wide sentinel as one principal. Authentication-
  flow `none` and unknown enum values retain distinct meanings; malformed operator-supplied
  account values use operator-keyed privacy-safe evidence aliases rather than raw input.
- Endpoint Security BitLocker and LAPS composites now retain complete assignment-intent
  classification. Malformed or unknown assignment targets produce a policy-scoped,
  sanitized `InvalidProviderData` gap and a `Partial` dataset, so unresolved targeting can
  never be laundered into complete evidence or an existential `Fail`.
- Composite datasets now use explicit TenantPulse provider-plan metadata instead of
  synthetic GraphKit `Pending` / `Walk` descriptors. Permission preflight includes every
  declared child operation, including Endpoint Security policy assignments, while the
  Windows data-processor disposition records no Graph operation or API version.
- Compliance and legacy device-configuration collection now joins every unambiguous policy
  to its authoritative assignment response. `TP.INT.0002` and `TP.INT.0004` require positive
  assignment evidence and ignore unrelated policy-scoped gaps. Relevant uncertainty degrades
  only when it can affect the result; `TP.INT.0004` bounds distinct possible candidates against
  its two-ring threshold and rejects coercible non-numeric deadline shapes.
- Endpoint Security collection now gaps absent or unrecognized template metadata instead
  of silently publishing authoritative empty results, and current security baselines are
  still collected when the independent legacy-template surface fails.
- Administrative Template expansion now honors a shared authentication abort before any
  descriptor or Graph work and gaps presentation values without stable ids instead of
  inventing random evidence identities. App Control wording now matches its confirmed-
  assignment behavior.
- Application report collection now request-body pages the Intune install summary through
  `TotalRowCount`, binds continuation pages to a native, nonblank service-returned `SessionId`,
  and discards missing, mismatched, or shape-switched continuations without persisting session
  metadata. It records incomplete totals and partial group metadata as gaps, stops every
  later report read on authentication failure, recursively scrubs tenant identifiers before
  persistence, rejects semantically unknown report matrices, and uses a canonical total-order
  tie-breaker for content-addressed rows.
- Graph collection now fails closed unless `Get-GraphObject -PassThruResult` returns exactly one complete `GraphKit.OperationResult`; null, rows-only, multiple, type-spoofed, and malformed results can no longer be persisted as `Collected`, while bounded partial rows retain indeterminate, truncation, and page-cap detail.
- Review finding 6 is implemented: Endpoint Security composite provenance now records the stable qualified primitive set `ConfigurationPolicy.ListBeta`, `ConfigurationPolicySetting.ListBeta`, and `ConfigurationPolicyAssignment.ListBeta`, independent of tenant policy count; setting and assignment gaps name their respective primitives explicitly.
- Direct, composite, and expansion collection paths now use one canonical Graph failure mapper. A request-time `403` is recorded as `Failed` / `PermissionDenied`; only `AuthenticationFailed` aborts subsequent network collection, while deadline expiration, cancellation, indeterminate certainty, permission denial, and provider failure remain explicit and isolated.
- Final review hardening now derives privacy from classified evidence; validates native-string
  assignment and Endpoint Security shapes; fails closed on malformed or contradictory
  BitLocker/LAPS, expansion, ARM, group-closure, and update-ring evidence; deduplicates rings
  by identity with deterministic evidence and exact gap attribution; and preserves both errors
  when expansion and manifest persistence fail together.
- Privacy completeness is now independent from the sharing boundary: ordinary evaluation
  documents remain `local-only`, only protected safe-share clones become `classified`, and HTML
  retains a prominent local-only warning unless the classification, native Boolean flags,
  classified boundary, and `safe-share-v1` protection provenance are exact. HTML publication now
  uses same-directory atomic replacement so a failed write preserves the prior good report.
- Release CI now uses a base-controlled `pull_request_target` gate that checksum-pins its
  scanner and reviewed `.gitleaksignore`, fetches PR heads only as passive Git objects, blocks
  PR changes to both trust-root files, and scans the full PR or push comparison range. The
  offline release gate also scans that protected workflow, every tracked content root including
  `.patch` and `.diff` handoffs, and root control files including `.gitignore`, for secret-shaped
  content and raw control bytes.
- Normal CI checks out and asserts the exact event commit before building: pull requests test the
  pull-request head SHA and pushes test `github.sha`, preventing a moving ref from being mistaken
  for exact-revision evidence.

### Changed

- The approved product-program completion work uses a unique successor identity. Published TenantPulse 0.2.0 and its exact GraphKit 0.3.0 dependency remain immutable.
- `Data.PartialDatasets` is a strict Function-only opt-in that requires `DatasetOutcomes`. Exactly six checks opt in: assignment-scoped checks `TP.INT.0002` and `TP.INT.0004` use authoritative assignment evidence and scope gaps by policy; universal checks `TP.INT.0013` and `TP.INT.0029` may Fail on a known offender but cannot Pass with gaps; existential checks `TP.INT.0014` and `TP.INT.0015` may Pass on a known witness but cannot Fail with gaps. BitLocker and LAPS witnesses require native Boolean values.
- The other 47 checks remain `NotApplicable` when their dataset status is `Partial`. For the six opt-ins, structurally valid non-decisive Partial evidence is `NotApplicable`; zero usable Partial rows, malformed outcomes or gaps, and rule-invalid rows remain `Error`.
- Findings schema `1.0`, snapshot schema `2.0.0`, and scoring model `1.0` are unchanged. This deterministic source/package tranche makes no new live-service or publication claim.
- Review finding 14 remains rejected/obsolete on first-party schema evidence: supported schema 1.0.0/1.1.0 writers could not emit `Partial`, so migration rejects that later state without rewriting the manifest.
- Classified JSON export now requires complete field classification before it emits a
  `privacy.boundary = "classified"` document. `-Redact`, `RedactDetailKeys`, and
  `Protect-PulseReason` remain the local-only compatibility layer; C0 D6 still leaves the public
  safe-share workflow undecided, and no public operator-key rotate cmdlet was added.
'@

        # Prerelease string of this module
        Prerelease =  ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
